name: "Hello Actions"
description: "Greet someone"
author: "thesse@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Germany"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
