name: A workflow for my Hello Germany file
on: push

jobs:
  build:
    name: Hello Germany action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Thomas"
      - uses: actions/upload-artifact
        with:
          name: first-artifact
          path: artifact/
